import { SOURCE_ROUTES } from '../charts/chartConfig';
import { fmtInt, fmtNum } from '../charts/format';

/**
 * Cross-section "bar + line" comparisons. The keys match `data.combos` from pulseModel.
 * Shared by Quick Glance (full chart) and the suggestions shown under each section.
 */
export const COMBO_VIEWS = {
  funding: {
    option: 'Funding vs publications',
    title: 'Research funding vs publications',
    subtitle: 'Sponsored funding (ICSR) against publications (Library)',
    to: SOURCE_ROUTES.funding,
    barKey: 'fundingCr',
    barName: 'Sponsored funding (₹ Cr)',
    barFormat: (v) => fmtNum(v, 1),
    lineKey: 'publications',
    lineName: 'Publications',
    lineFormat: (v) => fmtInt(v),
    headers: ['Academic year', 'Sponsored funding (Cr)', 'Publications'],
    filename: 'funding_vs_publications',
  },
  enrolment: {
    option: 'Enrolment vs placement',
    title: 'Enrolment vs placement',
    subtitle: 'Student intake (Academic) against placement rate (Placement)',
    to: SOURCE_ROUTES.placement,
    barKey: 'intake',
    barName: 'Student intake',
    barFormat: (v) => fmtInt(v),
    lineKey: 'placementPct',
    lineName: 'Placement %',
    lineFormat: (v) => `${fmtNum(v, 0)}%`,
    headers: ['Academic year', 'Student intake', 'Placement %'],
    filename: 'enrolment_vs_placement',
  },
  faculty: {
    option: 'Faculty vs publications',
    title: 'Faculty strength vs publications',
    subtitle: 'Teaching staff (Administrative) against publications (Library)',
    to: SOURCE_ROUTES.faculty,
    barKey: 'faculty',
    barName: 'Faculty strength',
    barFormat: (v) => fmtInt(v),
    lineKey: 'publications',
    lineName: 'Publications',
    lineFormat: (v) => fmtInt(v),
    headers: ['Academic year', 'Faculty strength', 'Publications'],
    filename: 'faculty_vs_publications',
  },
  patents: {
    option: 'Funding vs patents',
    title: 'Research funding vs patents',
    subtitle: 'Sponsored funding (ICSR) against patents filed',
    to: SOURCE_ROUTES.patents,
    barKey: 'fundingCr',
    barName: 'Sponsored funding (₹ Cr)',
    barFormat: (v) => fmtNum(v, 1),
    lineKey: 'patentsFiled',
    lineName: 'Patents filed',
    lineFormat: (v) => fmtInt(v),
    headers: ['Academic year', 'Sponsored funding (Cr)', 'Patents filed'],
    filename: 'funding_vs_patents',
  },
  industry: {
    option: 'Industry events vs consultancy',
    title: 'Industry events vs consultancy revenue',
    subtitle: 'Industry events held against consultancy revenue',
    to: SOURCE_ROUTES.funding,
    barKey: 'icsrEvents',
    barName: 'Industry events',
    barFormat: (v) => fmtInt(v),
    lineKey: 'consultancyCr',
    lineName: 'Consultancy revenue (₹ Cr)',
    lineFormat: (v) => fmtNum(v, 1),
    headers: ['Academic year', 'Industry events', 'Consultancy revenue (Cr)'],
    filename: 'industry_events_vs_consultancy',
  },
  innovation: {
    option: 'Startups vs innovation projects',
    title: 'Startups vs innovation projects',
    subtitle: 'Startups incubated against innovation projects',
    to: SOURCE_ROUTES.startups,
    barKey: 'startups',
    barName: 'Startups incubated',
    barFormat: (v) => fmtInt(v),
    lineKey: 'innovationProjects',
    lineName: 'Innovation projects',
    lineFormat: (v) => fmtInt(v),
    headers: ['Academic year', 'Startups incubated', 'Innovation projects'],
    filename: 'startups_vs_innovation_projects',
  },
};

export const isComboKey = (k) => typeof k === 'string' && Object.prototype.hasOwnProperty.call(COMBO_VIEWS, k);
